### ISSUE TITLE
Google Summer of Code 2020 

### ISSUE THREAD

**Issue by simonsan** [SFTtech/openage#1141]
What about applying for *SFTtech/openage* as a mentoring organization for the summer of code 2020 (#724) again? I think they announce the program in *November* and middle of *January* applications can be submitted.

Thoughts on this? Here a list of things to do from the 2017 application.

1. Gather mentors (that means YOU! if you contributed larger parts of the code
2. Think about work packages for students

**(examples from 2017, likely to change)**
  - [ ] The flow field pathfinder (#366)
  - [ ] Engine preparation for nyan (#734)
  - [ ] Networking with curve transmission (#530)

**possible work packages for students 2019**
  - [ ] Programming or designing the launcher
  - [ ] Python API for nyan
  - [ ] Modding Tool or nyan management tool (something for convenience like AGE3)

3. Create informational website for gsoc information, we could maybe use the github wiki if we're incompetent for web development.
4. Complete our application

Mentoring guide: https://google.github.io/gsocguides/mentor/org-application#

**Comment by heinezen** [comment]
I could supervise the creation of a modding tool, the integration of the editor or a Blender plugin. If there are things left to do for the converter, I would also do that.

**Comment by simonsan** [comment]
I think this can be closed. I will add it to `Zombie` for future applications.
