### ISSUE TITLE
Roadmap to release `0.5.0`

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1518]
Release `0.5.0` should be the milestone that uses a stable version of the new engine architecture. This means that all legacy code paths are removed and only the new engine components are used at runtime. Basically, these components are:

- [x] Renderer/Presenter (https://github.com/SFTtech/openage/pull/850, https://github.com/SFTtech/openage/pull/1492)
  - [x] OpenGL
  - ~~Vulkan~~ (done later)
- [x] Input system (https://github.com/SFTtech/openage/pull/1501)
- [x] Event System (https://github.com/SFTtech/openage/pull/1008)
- [x] Gamestate (https://github.com/SFTtech/openage/issues/1377, https://github.com/SFTtech/openage/pull/1515)
  - [x] Game Entity
  - [x] Components
  - [x] Systems
  - [x] Activities
- [x] Modpack Converter (https://github.com/SFTtech/openage/pull/1151)
  - [x] Converter fixes
- [x] Playtest demo (maybe using https://archive.org/details/AgeOfEmpiresIiTheConquerorsDemo)
- [x] Documentation

Legacy code will probably remain in the release and then removed in later releases one by one.
