### ISSUE TITLE
Render manager

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#34]
The rendermanager is some kind of batching mechanism to optimize the opengl calls.
This mainly means to reduce the amount of texture and shader switches for now.

Everything that should be rendered is submitted to the render manager. It orders the jobs and finally draws them in the optimized, but correct order.

The remaining features are tracked in the TODO-list **below**.

**Comment by franciscod** [comment]
dis is free software: 
> Ion is a portable suite of libraries and tools for building client applications,
especially graphical ones. It is small, fast, and robust, and is cross-platform
across many platforms and devices, including desktops, mobile devices, browsers,
and other embedded platforms.

https://github.com/google/ion

**Comment by TheJJ** [comment]
https://github.com/google/ion/tree/master/third_party hrrg

**Comment by TheJJ** [comment]
My attempt (will continue someday) is #287, but I'm currently working on nyan.
You can continue my branch and submit pulls there if anyone likes.

**Comment by zuntrax** [comment]
See #850

**Comment by Vtec234** [comment]
Here is a list of things to be done for the new renderer implementation:
- [x] Abstraction of render backend
  - [x] OpenGL 3.3 or higher
    - [ ] Use 4.x when available (optional)
    - [ ] Support ancient 2.x legacy (optional)
  - [ ] Vulkan (optional, #242)
- [ ] Render pipeline abstraction
  - [x] Textures
  - [x] Shaders
    - [x] Uniforms
    - [ ] Uniform buffers
    - [x] Vertex attributes
  - [x] Geometries
    - [x] Quad primitives
    - [ ] Circles
    - [ ] Smooth paths
    - [ ] Mesh importing (optional)
  - [x] Render targets
    - [x] Framebuffers
    - [ ] Renderbuffers (optional)
- [ ] Functionality
  - [x] Screenshot support
    - [ ] [PBO optimization](http://www.songho.ca/opengl/gl_pbo.html) for texture downloading (optional)
  - [x] Pixel-perfect unit hitbox for unit selection and damage areas (#368, #671 )
  - [ ] Outline rendering
  - [ ] Investigate why tree textures render incorrectly (#359, [maybe this?](http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/))
  - [ ] Fix #374
- [ ] Terrain rendering
  - [ ] Merge terrain texture into a single bitmap
  - [ ] Cache blending results (#154, #158)
  - [ ] Do as much as possible in shaders (#149)
  - [ ] Clip tiles properly (#141)
- [ ] Optimizations
  - [ ] [Occlusion queries](https://vertostudio.com/gamedev/?p=177)
  - [ ] Minimize OpenGL state changes (batch by shader, then by buffer)
  - [ ] Texture binpacking into atlas
  - [ ] Smooth zooming
- [ ] Integration
  - [ ] Rewrite all of drawing functionality to be expressed in terms of `Renderer`
    - [ ] Get rid of GL code everywhere except the rendering backend and the GUI
    - [ ] Write a `GameRenderer` that takes evaluations of curves at the current instant as input
  - [ ] GUI integration
    - [ ] TBD (#624)

**Comment by TheJJ** [comment]
we have added various components of a render manager meanwhile :)
